# Preperation of Kanban Host
#

---
- name: Configure Kanban Server
  hosts: all
  become: True
  tasks:
     - name: "Set German keymap for remote login"
       shell: "localectl set-keymap --no-convert de"

     - name: Update instance from repo
       yum:
         name: '*'
         state: latest
         update_cache: yes
         skip_broken: yes

     - name: Install epel-Packages
       yum:
         name: 
          - epel-release
         state: latest
         update_cache: no

     - name: "Update epel-release and dependencies"
       yum:
         name:               '*'
         state:              latest
         skip_broken:        yes

     - name: "Install useful tools"
       yum:
         name:
          - epel-release
          - vim
          - htop
          - nload
          - tmux
          - iftop
          - iotop
          - glances
          - fail2ban
          - nfs-utils
          - python-pip
          - docker
         state:              latest
         update_cache:       no

     - name: Copy deamon.json template to /etc/docker
       register: dockerconf
       template:
         src: docker.daemon.j2
         dest: '/etc/docker/daemon.json'
         owner: root
         group: root

     - name: Install dependent python modules
       pip:
         name: "{{item}}"
         state: present
       with_items:
         - docker-py==1.10.6
         - docker-compose==1.9.0

     - name: Restart docker
       systemd:
         state: restarted
         enabled: yes
         name: docker
       register: status_install

     - name: be sure firewalld is disabled
       systemd:
         name: firewalld
         enabled: no

     - name: be sure firewalld is stopped
       systemd:
         name: firewalld
         state: stopped
       ignore_errors: yes

     - name: Delete .bash_logout
       file:
         path: /etc/skel/.bash_logout
         state: absent

     - name: Check if colorls.sh exists
       stat: 
         path: /etc/profile.d/colorls.sh
       register: colorls_exists

     - debug:
         var: colorls_exists

     - name: Disable color in ls command
       command: mv /etc/profile.d/colorls.sh /etc/profile.d/colorls.sh_
       when: colorls_exists.stat.exists == True
       register: status_update

     - debug:
         var: status_update

     - name: Check if colorgrep.sh exists
       stat: 
         path: /etc/profile.d/colorgrep.sh
       register: colorgrep_exists

     - name: Disable color in grep command
       command: mv /etc/profile.d/colorgrep.sh /etc/profile.d/colorgrep.sh_
       when: colorgrep_exists.stat.exists == True
       register: status_update

     - debug:
         var: status_update

     - name: Kanbanik - create a directory for mongodb to store the data
       file:
         path: /data/localdb
         state: directory

     - name: Kanbanik - set the proper selinux policy on it
       sefcontext:
         target: '/data/localdb'
         setype: svirt_sandbox_file_t
         state: present

     - name: Restart System to reboot to newest Kernel
       shell: "sleep 5 && reboot"
       async: 1
       poll: 0

     - name: wait for 60 seconds
       pause:
         seconds: 60

     - name: wait for the system to reboot
       wait_for_connection:
         connect_timeout: 20
         sleep: 5
         delay: 5
         timeout: 180

     - name: Kanbanik - create a network for mongodb and kanbanik to talk on
       shell: |
         docker network create \
         --driver bridge \
         kanbanik_nw
       ignore_errors:                no

     - name: Kanbanik - get the mongodb
       shell: |
         docker pull mongo
       ignore_errors:                no

     - name: Kanbanik - run mongo
       shell: |
         docker run -d \
         -v /data/localdb:/data/db \
         --network=kanbanik_nw \
         --name mongodbserver \
         mongo
       ignore_errors:                no

     - name: Kanbanik - get the kanbanik
       shell: |
         docker pull jelkosz/kanbanik

     - name: Kanbanik - run kanbanik
       shell: |
         docker run -d \
         --network kanbanik_nw \
         -p 8080:8080 \
         -e MONGODB_HOST='mongodbserver' \
         jelkosz/kanbanik
