# Preperation of Bastion Host
#

---
- name: Configure Bastion Server
  hosts: all
  become: True
  tasks:
     - name: "Set German keymap for remote login"
       shell: "localectl set-keymap --no-convert de"

     - name: Generate Directory /home/linux/.ssh
       file:
         path: /home/linux/.ssh
         mode: 0700
         owner: linux
         group: linux
         state: directory

     - name: Copy access key for student server 
       copy:
         src: ../../keys/student.pem
         dest: /home/linux/.ssh/linux.student.pem
         mode: 0600
         owner: linux
         group: linux

     - name: AllowTcpForwarding of sshd
       replace:
         path: /etc/ssh/sshd_config
         regexp: '^AllowTcpForwarding no'
         replace: 'AllowTcpForwarding yes'

     - name: Update instance from repo
       yum:
         name: '*'
         state: latest
         update_cache: yes
         skip_broken: yes

     - name: Install epel-Packages
       yum:
         name: 
          - epel-release
         state: latest
         update_cache: no

     - name: "Update epel-release and dependencies"
       yum:
         name:               '*'
         state:              latest
         skip_broken:        yes

     - name: "Install useful tools"
       yum:
         name:
          - epel-release
          - vim
          - htop
          - nload
          - tmux
          - iftop
          - iotop
          - glances
          - fail2ban
          - nfs-utils
         state:              latest
         update_cache:       no


     - name: Install Intrusion Preventing System fail2ban
       yum:
         name: fail2ban 

     - name: "Update Config-File fail2ban"
       template:
         src:                "./templates/jail.local"
         dest:               "/etc/fail2ban/jail.local"
       register: status_install

     - debug:
         var: status_install

     - name: Start fail2ban
       systemd:
         state: started
         enabled: yes
         name: fail2ban
       register: status_install

     - debug:
         var: status_install
 
     - name: Delete .bash_logout
       file:
         path: /etc/skel/.bash_logout
         state: absent

     - name: Generate Directory /etc/skel/bin
       file:
         path: /etc/skel/bin
         mode: 0755
         state: directory

     - name: Generate Directory /etc/skel/.ssh
       file:
         path: /etc/skel/.ssh
         mode: 0700
         state: directory

     - name: Copy Key Files student.pub to authirized_keys
       copy:
         src: ../../keys/student.pub
         dest: /etc/skel/.ssh/authorized_keys
         mode: 0600

     - name: Check if colorls.sh exists
       stat: 
         path: /etc/profile.d/colorls.sh
       register: colorls_exists

     - debug:
         var: colorls_exists

     - name: Disable color in ls command
       command: mv /etc/profile.d/colorls.sh /etc/profile.d/colorls.sh_
       when: colorls_exists.stat.exists == True
       register: status_update

     - debug:
         var: status_update

     - name: Check if colorgrep.sh exists
       stat: 
         path: /etc/profile.d/colorgrep.sh
       register: colorgrep_exists

     - name: Disable color in grep command
       command: mv /etc/profile.d/colorgrep.sh /etc/profile.d/colorgrep.sh_
       when: colorgrep_exists.stat.exists == True
       register: status_update

     - debug:
         var: status_update
 
     - name: Create User trainer 
       user: 
         name: bastion
         shell: /bin/bash
         comment: User for Bastion
         group: 1000

     - name: Create Group training
       group:
         name: training
         state: present

     - name: Create User students
       user:
         name: "{{ item }}"
         state: present
         group: training
         shell: /bin/bash
         comment: Student of PaaS Training
       loop:
         - student01
         - student02
         - student03
         - student04
         - student05
         - student06
         - student07
         - student08
         - student09
         - student10
         - student11
         - student12
         - student13
         - student14
         - student15
         - student16
         - student17
         - student18
         - student19
         - student20
         - student21
         - student22
         - student23
         - student24
         - student25
         - student26
         - student27
         - student28
         - student29
         - student30
         - student31

     - name: Restart System to reboot to newest Kernel
       shell: "sleep 5 && reboot"
       async: 1
       poll: 0

     - name: wait for 60 seconds
       pause:
         seconds: 60

     - name: wait for the system to reboot
       wait_for_connection:
         connect_timeout: 20
         sleep: 5
         delay: 5
         timeout: 180

